namespace tsbindgen.Render;

/// <summary>
/// Synthetic declaration generated by analysis passes.
/// Examples: intersection interfaces, wrapper types, compatibility overloads.
/// </summary>
public sealed record HelperDeclaration(
    HelperKind Kind,
    string Name,
    string TsDefinition);

/// <summary>
/// Kind of helper declaration.
/// </summary>
public enum HelperKind
{
    IntersectionInterface,
    WrapperInterface,
    CompatibilityOverload,
    BaseInterface
}
